version: 0.2

phases:
  build:
    commands:
      - chmod 755 gradlew
      - ./gradlew assembleDebug
      - ls -l
      - ls -l app/build/outputs/apk/debug
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
